name: Build release binary

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write # Needed to create releases
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-latest,
              toolchain: '1.77.2',
              args: ''
            }
          # - {  # Example configuration for Ubuntu (adjust as needed)
          #    target: x86_64-unknown-linux-gnu,
          #    os: ubuntu-latest,
          #    toolchain: '1.77.2',
          #    args: '--target x86_64-unknown-linux-gnu',
          #  }
          # - {   # Example macOS configuration (adjust as needed)
          #    target: aarch64-apple-darwin,
          #    os: macos-latest,
          #    toolchain: '1.77.2',
          #    args: '--target aarch64-apple-darwin',
          #  }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain ${{ matrix.platform.toolchain }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.platform.toolchain }}
          target: ${{ matrix.platform.target }}
          components: rustfmt, clippy

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Tauri App (Release) - Cargo
        run: |
          cargo tauri build --release

        env:
          TAURI_PLATFORM: ${{ matrix.platform.target }} # Specify the target platform for Tauri

      - name: Create Tauri Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          #TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }} # For signing (optional)
          #TAURI_SIGNING_PASSWORD: ${{ secrets.TAURI_SIGNING_PASSWORD }} # For signing (optional)
        with:
          tagName: "v__VERSION__" # Tag name must have v prefix
          releaseName: "MasterMath v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.platform.args }}
          path: src-tauri/target/release/bundle # path to the built application
