name: Build release binary

on:
  push:
    branches:
      - develop
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-latest,
              toolchain: '1.77.2',
              args: ''
            }
          # - {
          #     target: x86_64-unknown-linux-gnu,
          #     os: ubuntu-latest,
          #     toolchain: '1.77.2',
          #     cross: false,
          #     command: 'test'
          #   }
          # - {
          #     target: aarch64-apple-darwin,
          #     os: macos-14,
          #     toolchain: '1.77.2',
          #     cross: false,
          #     command: 'test'
          #   }
          # - {
          #     target: aarch64-apple-ios,
          #     os: macos-latest,
          #     toolchain: '1.77.2',
          #     cross: false,
          #     command: 'build'
          #   }

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      # - name: install dependencies (ubuntu only)
      #   if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.platform.toolchain }}
          targets: ${{ matrix.platform.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: npm install # change this to npm or pnpm depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: master-math-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'MasterMath v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.platform.args }}
          path: src-tauri/target/release/bundle # path to the built application
